spring:
  application:
    name: ServiceRegistry
eureka:
  instance:
    hostname: localhost
    #avoid to register itself false
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761